<?php

namespace AppBundle\Repository;

/**
 * AjouterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AjouterRepository extends \Doctrine\ORM\EntityRepository
{
}
