<?php

namespace AppBundle\Repository;

/**
 * GalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieRepository extends \Doctrine\ORM\EntityRepository
{
     public function getNb3() {
  
        return $this->createQueryBuilder('l')
  
                        ->select('COUNT(l)')
  
                        ->getQuery()
  
                        ->getSingleScalarResult();
  
    }
}
