<?php

namespace AppBundle\Repository;

/**
 * ImagesCarousselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesCarousselRepository extends \Doctrine\ORM\EntityRepository
{
}
