<?php

namespace AppBundle\Repository;

/**
 * ImgProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgProfilRepository extends \Doctrine\ORM\EntityRepository
{
}
