<?php

namespace AppBundle\Repository;

/**
 * ProjetsDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
