<?php

namespace AppBundle\Repository;

/**
 * ProjetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsRepository extends \Doctrine\ORM\EntityRepository
{
public function getNb() {
  
        return $this->createQueryBuilder('l')
  
                        ->select('COUNT(l)')
  
                        ->getQuery()
  
                        ->getSingleScalarResult();
  
    }
}


