<?php

namespace AppBundle\Repository;

/**
 * ProjetsPrintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsPrintRepository extends \Doctrine\ORM\EntityRepository
{
}
