# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
     # celui qui a un ROLE_ADMIN à aussi les privilèges du USER standard ;)
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
         # ici gestionUser est defini pour une auth via database
       
         # ici on peut coder en dur des users         
        in_memory:
            memory: 
                users:
                    onepale:
                        password: onepale1
                        
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern : ^/
            anonymous: true
            provider: in_memory
            # le formulaire de login pour que symfony sache où il campe
            form_login:
                check_path: loginCheck
                login_path: admin
            logout:
                path: loginOut
                target: /
            # important !!! renseignez le provider a utiliser !
           # Firewall pour la zone d'administration   
        # ici c'est avec le provider codé en dur 
        # quand on accede à : www.monsite.fr/admin
        # pas d'annonyme !        
        administration:
            pattern: ^/admin
            anonymous: false
            provider: in_memory
            # le formulaire de login pour que symfony sache où il campe
            form_login:
                check_path: loginCheck
                login_path: admin
            logout:
                path: loginOut
                target: /
            # activate different ways to authenticate
              # ici c'est le cryptage des mots de passe (ou pas)            
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AdminBundle\Entity\User:
            algorithm: plaintext
            ignore_case: false
           
    access_control:   
        # Un admin ou un user classique peut ajouter une annonce ... quelque chose d'étrange est ici ....
        - { path: ^/admin , roles: [ROLE_ADMIN] }       
        # seul un admin peut ajouter une categorie
        
            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
            # evidement on peut jouer sur differents niveaux de restrictions   
             
            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
